Feat/plz tuning max
Speedfan94/PDS_Project pull request #85
Opened 2020-06-04 18:29 UTC by MaxStroh

implements geo cleaning with geopandas

**IMPORTANT:**
We will need to call "conda install rtree" to be able to use these methods.

Currently in discussion whether we are allowed to use these methods

2020-06-04 18:29 UTC, MaxStroh commented
I will merged the latest dev updates into this branch tomorrow!

2020-06-05 07:02 UTC, Speedfan94 requested changes
Please add docstrings and rename plz to postalcode, then i am fine :-)

2020-06-05 07:02 UTC, Speedfan94 commented on nextbike/datapreparation/geo_clean.py
> +    df_with_start_plz.rename({"plz": "plz_start"}, axis=1, inplace=True)
rename plz to postalcode

2020-06-05 07:02 UTC, Speedfan94 commented on nextbike/datapreparation/geo_clean.py
> +    gdf_geo_end_pos = gpd.GeoDataFrame(df_with_start_plz,
plz --> postalcoda

2020-06-05 07:02 UTC, Speedfan94 commented on nextbike/datapreparation/geo_clean.py
> +    df_with_all_plz.rename({"plz": "plz_end"}, axis=1, inplace=True)
plz --> postalcode

2020-06-05 07:02 UTC, Speedfan94 commented on nextbike/datapreparation/geo_clean.py
>      # Add PLZ to trip and drop trips without start or end PLZ
Change PLZ To Postalcode

2020-06-05 07:02 UTC, Speedfan94 commented on nextbike/datapreparation/geo_clean.py
Add docstring

2020-06-05 08:13 UTC, MaxStroh commented on nextbike/datapreparation/geo_clean.py
> +    df_with_start_plz.rename({"plz": "plz_start"}, axis=1, inplace=True)
Done with merge from dev

2020-06-05 08:13 UTC, MaxStroh commented on nextbike/datapreparation/geo_clean.py
> +    gdf_geo_end_pos = gpd.GeoDataFrame(df_with_start_plz,
Done with merge from dev

2020-06-05 08:13 UTC, MaxStroh commented on nextbike/datapreparation/geo_clean.py
> +    df_with_all_plz.rename({"plz": "plz_end"}, axis=1, inplace=True)
Done with merge from dev

2020-06-05 08:13 UTC, MaxStroh commented on nextbike/datapreparation/geo_clean.py
>      # Add PLZ to trip and drop trips without start or end PLZ
Done with merge from dev

2020-06-05 08:13 UTC, MaxStroh commented on nextbike/datapreparation/geo_clean.py
Done with merge from dev

2020-06-05 08:15 UTC, MaxStroh commented
Done! Please review :D

2020-06-05 08:19 UTC, Speedfan94 approved these changes
all changes approved :-)

2020-06-05 08:24 UTC, weisske approved these changes
The world will love it

2020-06-05 08:24 UTC, weisske commented on nextbike/datapreparation/geo_clean.py
> +                                                                     p_df["Latitude_start"]))
Genius

2020-06-05 08:27 UTC, mulko93 approved these changes
nice algorithm and code style

2020-06-05 08:34 UTC, merged